### ISSUE TITLE
composer require league/oauth2-craftid does not find package

### ISSUE THREAD

**Issue by sonjaq** [craftcms/oauth2-craftid#1]
It appears that the steps in the `README` no longer work. Searching packagist.org or `composer search` for any variant of `craftid` or `oauth-craft` yields no results.

### Steps
1. Attempt to use the installation instructions provided
 - `composer require league/oauth2-craftid`
2. Search packagist.org for a similarly named package
2. Observe that composer cannot locate the package

### Expected
1. Updated installation instructions should be provided
**OR**
2. `league/oauth2-craftid` should be published via packagist.org

**Comment by lukeholder** [comment]
This repository has been moved to the `craftcms` github organisation and published to packagist.

Once packagist picks it up you will be able to do: `composer require craftcms/oauth2-craftid`

The readme has been updated.
